In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('Diabetes_data.csv')
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [3]:
df = data.copy()

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [5]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
df['Outcome'].sum()

268

In [7]:
df['Outcome'].count()-df['Outcome'].sum()

500

## Shuffle the data

In [8]:
from sklearn.utils import shuffle

In [9]:
X = np.array(df.iloc[:,:-1])

In [10]:
y = np.array(df.iloc[:,-1])

In [11]:
X,y = shuffle(X,y, random_state=42)
X,y

(array([[  6.   ,  98.   ,  58.   , ...,  34.   ,   0.43 ,  43.   ],
        [  2.   , 112.   ,  75.   , ...,  35.7  ,   0.148,  21.   ],
        [  2.   , 108.   ,  64.   , ...,  30.8  ,   0.158,  21.   ],
        ...,
        [ 10.   , 101.   ,  86.   , ...,  45.6  ,   1.136,  38.   ],
        [  0.   , 141.   ,   0.   , ...,  42.4  ,   0.205,  29.   ],
        [  0.   , 125.   ,  96.   , ...,  22.5  ,   0.262,  21.   ]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
        0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
        0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
        0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
        1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
        1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
        0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
        1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
        0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
        1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
        0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
        0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0],
       dtype=int64))

In [12]:
columns = df.columns[:-1]
data_shuffled = pd.DataFrame(X, columns=columns)
data_shuffled['Outcome'] = y
data_shuffled

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,98.0,58.0,33.0,190.0,34.0,0.430,43.0,0
1,2.0,112.0,75.0,32.0,0.0,35.7,0.148,21.0,0
2,2.0,108.0,64.0,0.0,0.0,30.8,0.158,21.0,0
3,8.0,107.0,80.0,0.0,0.0,24.6,0.856,34.0,0
4,7.0,136.0,90.0,0.0,0.0,29.9,0.210,50.0,0
...,...,...,...,...,...,...,...,...,...
763,5.0,139.0,64.0,35.0,140.0,28.6,0.411,26.0,0
764,1.0,96.0,122.0,0.0,0.0,22.4,0.207,27.0,0
765,10.0,101.0,86.0,37.0,0.0,45.6,1.136,38.0,1
766,0.0,141.0,0.0,0.0,0.0,42.4,0.205,29.0,1
767,0.0,125.0,96.0,0.0,0.0,22.5,0.262,21.0,0

In [13]:
type(data_shuffled['Outcome'][0])

numpy.int64

## Balancing the data

In [14]:
indeces_to_remove = []
counter = 0
for outcomes in range(data_shuffled.shape[0]):
    if data_shuffled['Outcome'].iloc[outcomes] == 0:
        counter += 1
        if counter > 268:
            indeces_to_remove.append(outcomes)
balanced_data = np.delete(data_shuffled, indeces_to_remove, axis = 0)

In [15]:
data_shuffled.columns.values

array(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness',
       'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype=object)

In [16]:
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness',
       'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']

In [17]:
balanced_df = pd.DataFrame(balanced_data, columns=columns)

In [18]:
balanced_df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,98.0,58.0,33.0,190.0,34.0,0.430,43.0,0.0
1,2.0,112.0,75.0,32.0,0.0,35.7,0.148,21.0,0.0
2,2.0,108.0,64.0,0.0,0.0,30.8,0.158,21.0,0.0
3,8.0,107.0,80.0,0.0,0.0,24.6,0.856,34.0,0.0
4,7.0,136.0,90.0,0.0,0.0,29.9,0.210,50.0,0.0
...,...,...,...,...,...,...,...,...,...
531,10.0,148.0,84.0,48.0,237.0,37.6,1.001,51.0,1.0
532,9.0,112.0,82.0,32.0,175.0,34.2,0.260,36.0,1.0
533,11.0,138.0,74.0,26.0,144.0,36.1,0.557,50.0,1.0
534,10.0,101.0,86.0,37.0,0.0,45.6,1.136,38.0,1.0
535,0.0,141.0,0.0,0.0,0.0,42.4,0.205,29.0,1.0

In [19]:
balanced_df.info

<bound method DataFrame.info of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6.0     98.0           58.0           33.0    190.0  34.0
1            2.0    112.0           75.0           32.0      0.0  35.7
2            2.0    108.0           64.0            0.0      0.0  30.8
3            8.0    107.0           80.0            0.0      0.0  24.6
4            7.0    136.0           90.0            0.0      0.0  29.9
..           ...      ...            ...            ...      ...   ...
531         10.0    148.0           84.0           48.0    237.0  37.6
532          9.0    112.0           82.0           32.0    175.0  34.2
533         11.0    138.0           74.0           26.0    144.0  36.1
534         10.0    101.0           86.0           37.0      0.0  45.6
535          0.0    141.0            0.0            0.0      0.0  42.4

     DiabetesPedigreeFunction   Age  Outcome
0                       0.430  43.0      0.0
1                       0.148  21.0      0.0
2                       0.158  21.0      0.0
3                       0.856  34.0      0.0
4                       0.210  50.0      0.0
..                        ...   ...      ...
531                     1.001  51.0      1.0
532                     0.260  36.0      1.0
533                     0.557  50.0      1.0
534                     1.136  38.0      1.0
535                     0.205  29.0      1.0

[536 rows x 9 columns]>

## Shuffle again

In [20]:
## since excess zeroes are removed, most of the last rows of the data is 1. we have to reshuffle to avoid overfitting

In [21]:
X = np.array(balanced_df.iloc[:,:-1])
y = np.array(balanced_df.iloc[:,-1])

In [22]:
X,y = shuffle(X,y, random_state=42)
X,y

(array([[  4.   , 110.   ,  66.   , ...,  31.9  ,   0.471,  29.   ],
        [  1.   , 109.   ,  60.   , ...,  25.4  ,   0.947,  21.   ],
        [  2.   ,  84.   ,   0.   , ...,   0.   ,   0.304,  21.   ],
        ...,
        [  4.   ,  90.   ,   0.   , ...,  28.   ,   0.61 ,  31.   ],
        [  6.   , 134.   ,  70.   , ...,  35.4  ,   0.542,  29.   ],
        [ 13.   , 126.   ,  90.   , ...,  43.4  ,   0.583,  42.   ]]),
 array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1.,
        0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0.,
        1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1.,
        1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0.,
        0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1.,
        0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
        0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
        1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1.,
        1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1., 0.,
        1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1.,
        0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
        1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1.,
        0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1.,
        0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0.,
        0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
        0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1.,
        0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0.,
        0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
        1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1.,
        1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1.,
        1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0.,
        1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
        0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1.,
        0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1.,
        0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0.,
        0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1.,
        0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0.,
        1., 1., 0., 0., 0., 0., 0., 1., 1.]))

In [23]:
columns = balanced_df.columns[:-1]
diabetes_data = pd.DataFrame(X, columns=columns)
diabetes_data['Outcome'] = y
diabetes_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,4.0,110.0,66.0,0.0,0.0,31.9,0.471,29.0,0.0
1,1.0,109.0,60.0,8.0,182.0,25.4,0.947,21.0,0.0
2,2.0,84.0,0.0,0.0,0.0,0.0,0.304,21.0,0.0
3,5.0,117.0,92.0,0.0,0.0,34.1,0.337,38.0,0.0
4,0.0,119.0,64.0,18.0,92.0,34.9,0.725,23.0,0.0
...,...,...,...,...,...,...,...,...,...
531,4.0,83.0,86.0,19.0,0.0,29.3,0.317,34.0,0.0
532,2.0,141.0,58.0,34.0,128.0,25.4,0.699,24.0,0.0
533,4.0,90.0,0.0,0.0,0.0,28.0,0.610,31.0,0.0
534,6.0,134.0,70.0,23.0,130.0,35.4,0.542,29.0,1.0
535,13.0,126.0,90.0,0.0,0.0,43.4,0.583,42.0,1.0

## checkpoint

In [24]:
data = diabetes_data.copy()

In [25]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,4.0,110.0,66.0,0.0,0.0,31.9,0.471,29.0,0.0
1,1.0,109.0,60.0,8.0,182.0,25.4,0.947,21.0,0.0
2,2.0,84.0,0.0,0.0,0.0,0.0,0.304,21.0,0.0
3,5.0,117.0,92.0,0.0,0.0,34.1,0.337,38.0,0.0
4,0.0,119.0,64.0,18.0,92.0,34.9,0.725,23.0,0.0
...,...,...,...,...,...,...,...,...,...
531,4.0,83.0,86.0,19.0,0.0,29.3,0.317,34.0,0.0
532,2.0,141.0,58.0,34.0,128.0,25.4,0.699,24.0,0.0
533,4.0,90.0,0.0,0.0,0.0,28.0,0.610,31.0,0.0
534,6.0,134.0,70.0,23.0,130.0,35.4,0.542,29.0,1.0
535,13.0,126.0,90.0,0.0,0.0,43.4,0.583,42.0,1.0

In [26]:
data.to_csv('diabetes_preprocessed.csv', index = False)